runtime: nodejs16
# handlers:
#   - url: /(.*\..+)$
#   static_files: build/\1
#   upload: build/(.*\..+)$
#   - url: /.*
#   static_files: build/index.html
#   upload: build/index.html

# handlers:
# - url: /.*
# static_files: build/index.html
# upload: build/(.*\..+)$
# - url: /
# static_dir: build

handlers:
    - url: /eCommerce-App/
      static_files: build/index.html
      upload: build/index.html
    - url: /eCommerce-App/(.*)$
      static_files: build/\1
      upload: build/(.*)
